import './globals.css'
import { Inter } from 'next/font/google'
import { GoogleTagManager } from '@next/third-parties/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <GoogleTagManager gtmId="GTM-TJT6H9LK" />
      <body className={inter.className}>
     


<noscript><iframe src="https://www.googletagmanager.com/ns.html?id=GTM-TJT6H9LK"
height="0" width="0" style={{ display: "none", visibility: "hidden" }}></iframe></noscript>
        
        {children}</body>
    </html>
  )
}
